config/routes.rb
Rails.application.routes.draw do
  

  resources :requests do
    collection do
      get 'manage_all'
      get 'approve/:id' => :approve, as: 'approve'
    end
  end

  resources :regions do
    collection do
      get 'manage_all'
    end
  end

  resources :users do
    collection do
      get 'show/:id' => :show, as: 'show'
      get 'edit/:id' => :edit, as: 'edit'
      patch 'update/:id' => :update, as: 'update'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	resources :distributions


	root 'welcome#index'
  get '/about', to: "welcome#about"

end

app/models/user.rb
class User < ApplicationRecord
	include Clearance::User
	has_and_belongs_to_many :regions
	has_many :requests

end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :set_user, only: [:show, :edit, :update]

	# Manage user profile
	def show
	end

	def edit
	end

	def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user].permit(:created_at, :updated_at, :email, :password, :confirmation_token, :remember_token, :firstname, :lastname, :default_region, :is_admin, :is_super_admin)
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :firstname, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :lastname, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "form-control"  %>
  </div>

	<p>
	  <strong>Admin?</strong>
	  <% if @user.is_admin %>
	  	Yes
	  <% else %>
	  	No
	  <% end %>
	</p>
	<br/>
	<p>Distributions will be centred in and saved under this city.</p>
  <div class="form-group">
    <%= f.label :current_distribution_city %>&nbsp;&nbsp;&nbsp;
    <%= f.collection_select :default_region, @user.regions, :id, :name, include_blank: true, :class => "form-control", :selected => @user.default_region %>
  </div>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-info"  %>
  </div>
<% end %>

<br />

app/views/users/edit.html.erb
<h1>Editing User</h1>
<br/>

<%= render 'form', user: @user %>

<%= link_to 'Show user settings', user_path(:id => current_user.id) %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <div class="form-group">
     <%= form.label :first_name %>
     <%= form.text_field :firstname, type: 'text', :class => "form-control" %>
   </div>
   
   <div class="form-group">
     <%= form.label :last_name %>
     <%= form.text_field :lastname, type: 'text', :class => "form-control" %>
   </div>
   
   <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email', :class => "form-control" %>
    </div>
    
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, :class => "form-control" %>
   </div>

    <div class="form-actions">
      <%= form.submit :class => "btn btn-info" %>
    </div>

    <br />

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %> || 
      <%= link_to t(".forgot_password"), new_password_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Your User Settings</h1>

<br />

<p>
  <strong>First name:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Admin?</strong>
  <% if @user.is_admin %>
  	Yes
  <% else %>
  	No
  <% end %>
</p>

<p>
  <strong>Default city that distributions will be saved to:</strong><br/><br/>
  <% if @user.default_region %>
    <%= Region.find(@user.default_region).name %>
  <% else %>
    You have not been approved for any cities yet. <%= link_to "Click to join a city", new_request_path %>
  <% end %>
</p>

</br>

<%= link_to "Edit User", edit_users_path(:id => current_user.id), :class => "btn btn-info" %>