config/routes.rb
Rails.application.routes.draw do
  

  resources :requests do
    collection do
      get 'manage_all'
      get 'approve/:id' => :approve, as: 'approve'
    end
  end

  resources :regions do
    collection do
      get 'manage_all'
    end
  end

  resources :users do
    collection do
      get 'show/:id' => :show, as: 'show'
      get 'edit/:id' => :edit, as: 'edit'
      patch 'update/:id' => :update, as: 'update'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	resources :distributions


	root 'welcome#index'
  get '/about', to: "welcome#about"

end

app/models/distribution.rb
class Distribution < ApplicationRecord
	has_one :region
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  before_action :require_login
  before_action :set_distribution, only: [:show, :edit, :update, :destroy]
  before_action :set_default_coordinates


  # GET /distributions
  # GET /distributions.json
  def index
    # TODO add all the regions the user is subscribed to
    @distributions = Distribution.where(:region_id => current_user.regions)
  end

  # GET /distributions/1
  # GET /distributions/1.json
  def show
    @editing = false
  end

  # GET /distributions/new
  def new
    @distribution = Distribution.new
    @editing = true
  end

  # GET /distributions/1/edit
  def edit
    @editing = true
  end

  # POST /distributions
  # POST /distributions.json
  def create
    @distribution = Distribution.new(distribution_params)

    respond_to do |format|
      if @distribution.save
        format.html { redirect_to @distribution, notice: 'Distribution was successfully created.' }
        format.json { render :show, status: :created, location: @distribution }
      else
        format.html { render :new }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distributions/1
  # PATCH/PUT /distributions/1.json
  def update
    respond_to do |format|
      if @distribution.update(distribution_params)
        format.html { redirect_to @distribution, notice: 'Distribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @distribution }
      else
        format.html { render :edit }
        format.json { render json: @distribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distributions/1
  # DELETE /distributions/1.json
  def destroy
    @distribution.destroy
    respond_to do |format|
      format.html { redirect_to distributions_url, notice: 'Distribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_default_coordinates
      # Default is set to Leeds for any user
      default_latitude = 53.8008
      default_longitude = -1.5491

      @latitude = current_user.default_region ? Region.find(current_user.default_region).latitude : default_latitude
      @longitude = current_user.default_region ? Region.find(current_user.default_region).longitude : default_longitude
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_distribution
      @distribution = Distribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distribution_params
      params.require(:distribution).permit(:date, :participants, :quantity, :routes, :comments, :region_id)
    end
end

app/helpers/distributions_helper.rb
module DistributionsHelper
end

app/views/distributions/_form.html.erb
<%= form_for(distribution) do |f| %>
  <% if distribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distribution.errors.count, "error") %> prohibited this distribution from being saved:</h2>

      <ul>
      <% distribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_select :date, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :participants %>
    <%= f.number_field :participants, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, :class => "form-control"  %>
  </div>

  <!-- If creating a new distribution or viewing one, do not allow editing. -->
  <% if @editing %>
    <p>
      Select the routes covered by clicking at the starting and ending point of each block to draw a line. Routes do not need to be closed loops. To end a path and begin another one in another location, click the endpoint again.
    </p>

    <br />

    <!-- Editing panel - clear map, pen colour, etc. -->
    <div id="floating-panel">
      <input onclick="clearMap();" type=button value="Clear map">
    </div>

  <% end %>

  <div class="form-group hidden-routes" id="distribution-routes">
    <%= f.label :routes %>
    <%= f.text_field :routes %>
  </div>

  <div class="form-group hidden-routes" id="distribution-default-region">
    <%= f.label :region_id %>
    <input class="form-control" type="number" name="distribution[region_id]" id="distribution_default_id" value="<%= current_user.default_region %>">
  </div>

  <div id="editing-field" class="editing-field"><%= @editing %></div>
  <div id="latitude-field" class="latitude-field"><%= @latitude %></div>
  <div id="longitude-field" class="longitude-field"><%= @longitude %></div>

  <%= render :partial => "googlemap", editing: @editing %>
  
  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, :class => "form-control" %>
  </div>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
  <br/>
<% end %>

app/views/distributions/_googlemap.html.erb
<div id="googlemap"></div>

<br />

<script type="text/javascript">	

	// Handle for the routes data to be added to the page
	var routesHandle = document.getElementById("distribution_routes");
	var routes = [];

	// All paths, for clearing map.
	var allOverlays = [];

	// Determine what functions to call based on if allowing drawing or not.
	var editing = false;
	if(document.getElementById("editing-field").textContent == "true") {
		editing = true;
	}

	var map, drawingManager;

	// Initiates the map 
	function initMap() {

		var defaultLatitude = document.getElementById("latitude-field");
		var defaultLongitude = document.getElementById("longitude-field");

		if(defaultLongitude && defaultLatitude) {
			defaultLatitude = defaultLatitude.textContent;
			defaultLongitude = defaultLongitude.textContent;
		}

		var defaultZoom = 12;
		var defaultCenter;
		if(defaultLatitude && defaultLongitude) {
			defaultCenter = new google.maps.LatLng(defaultLatitude, defaultLongitude);
		} else {
			defaultCenter = new google.maps.LatLng(53.8008, -1.5491);
		}

		// Create map and add controls
		var mapOptions = {
			center: defaultCenter,
			zoom: defaultZoom,
			mapTypeId: google.maps.MapTypeId.ROADMAP,
			scrollwheel: true,
			scaleControl: true
		};

		map = new google.maps.Map(document.getElementById('googlemap'), mapOptions);
		
		if(editing) {
			drawingManager = new google.maps.drawing.DrawingManager({
				drawingMode: google.maps.drawing.OverlayType.Polyline,
				drawingControl: true,
				drawingControlOptions: {
					position: google.maps.ControlPosition.TOP_CENTER,
					drawingModes: ['polyline'],
				},

				polylineOptions: {
					strokeColor: '#FFFF00',
					strokeOpacity: 0.5,
					strokeWeight: 10,
					clickable: false,
					editable: true,
					zIndex: 1
				}
			});

			drawingManager.setMap(map);
			console.log(editing);
		
			// Add a listener for the completed polyline event.
	  		google.maps.event.addListener(drawingManager, 'polylinecomplete', addLine);
		}
	
		displayPaths();
	}

	// Handles the saving of a polyline once it is completed.
	function addLine(polyline) {
		allOverlays.push(polyline);

		var path = polyline.getPath().getArray();
		var new_path = [];

		// Construct the new array of paths.
		for (var i = path.length - 1; i >= 0; i--) {
			new_path.push([path[i].lat(), path[i].lng()]);
		}

		routes.push(new_path); // Array of arrays [[lat, lng], [lat2, lng2]... ]
		routesHandle.value = JSON.stringify(routes);
	}

	// Fetches the paths from routes and displays them.
	function displayPaths() {
    	
    	if(routesHandle.value == "") {
    		return;
    	}

		routes = JSON.parse(routesHandle.value);
		
		// Now iterate through all the polylines and draw them on the map.
		for(var i = 0; i < routes.length; i++) {
			var newPath = [];
			for (var j = 0; j < routes[i].length; j++) {
				// routes[i][j] [[lat, lng], [lat2, lng2]...]
				newPath.push({ lat: routes[i][j][0], lng: routes[i][j][1] });
			}

			var poly = new google.maps.Polyline({
				path: newPath,
				strokeColor: '#FFFF00',
				strokeWeight: 10,
				strokeOpacity: 0.5,
				editable: false,
				clickable: false,
				zIndex: 5,
			});

			allOverlays.push(poly);
			poly.setMap(map);
		}
 	}

	// Removes the routes and clears the map.
	function clearMap() {
		routesHandle.value = "";
		routes = [];
		for (var i = allOverlays.length - 1; i >= 0; i--) {
			allOverlays[i].setMap(null);
		}

		allOverlays = [];
	}
	
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHL2s9qdWZH4JXh0abnr9FJtAE_2A9GZQ&libraries=drawing&callback=initMap"
         async defer></script>

app/views/distributions/edit.html.erb
<h1>Editing Distribution</h1>

<br />

<%= render 'form', distribution: @distribution %>

<br />
<%= link_to 'Show', @distribution %> |
<%= link_to 'Back', distributions_path %>
<br />

app/views/distributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributions</h1>

<p>You are currently viewing all distributions for cities you have joined.</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>City</th>
      <th>Participants</th>
      <th>Quantity</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributions.each_with_index do |distribution, index| %>
      <tr>
        <td><%= distribution.date %></td>
        <td><%= Region.find(distribution.region_id).name %></td>
        <td><%= distribution.participants %></td>
        <td><%= distribution.quantity %></td>
        <td><%= distribution.comments %></td>
        <td><%= link_to 'Show', distribution %></td>
        <td><%= link_to 'Edit', edit_distribution_path(distribution) %></td>
        <td><%= link_to 'Delete', distribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Distribution', new_distribution_path, :class => "btn btn-info" %>

app/views/distributions/new.html.erb
<h1>New Distribution</h1>
<br/>
<%= render 'form', distribution: @distribution, current_id: @current_id %>

<%= link_to 'Back', distributions_path %>
<br />

app/views/distributions/show.html.erb
<h1>Showing Distribution</h1>

<br />

<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @distribution.date %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @distribution.participants %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @distribution.quantity %>
</p>

<div class="hidden-routes" id="distribution-routes">
  <input type="text" value="<%= @distribution.routes %>" name="distribution[routes]" id="distribution_routes">
</div>
<div id="editing-field" class="editing-field"><%= @editing %></div>

<%= render :partial => "googlemap" %>

<p>
  <strong>Comments:</strong>
  <%= @distribution.comments %>
</p>

<%= link_to 'Edit', edit_distribution_path(@distribution) %> |
<%= link_to 'Back', distributions_path %>