config/routes.rb
Rails.application.routes.draw do
  

  resources :requests do
    collection do
      get 'manage_all'
      get 'approve/:id' => :approve, as: 'approve'
    end
  end

  resources :regions do
    collection do
      get 'manage_all'
    end
  end

  resources :users do
    collection do
      get 'show/:id' => :show, as: 'show'
      get 'edit/:id' => :edit, as: 'edit'
      patch 'update/:id' => :update, as: 'update'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	resources :distributions


	root 'welcome#index'
  get '/about', to: "welcome#about"

end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user
	has_one :region
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :approve]
  before_action :require_login
  before_action :require_admin, only: [:manage_all, :approve]

  # GET /requests
  # GET /requests.json
  def index
    @requests = current_user.requests
  end

  # For the admin to approve requests
  def manage_all
    @requests = Request.all
  end

  # Admin approves a pending request
  def approve

    user = User.find(@request.user_id)
    user.regions << Region.find(@request.city)
    if user.regions.length == 1
      user.default_region = @request.city
    end
    
    user.save

    @request.destroy
    respond_to do |format|
      format.html { redirect_to manage_all_requests_path, notice: 'Request was successfully approved.' }
      format.json { head :no_content }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.country = Region.find(request_params[:city]).country

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update

    success = @request.update(request_params)
    if success
      @request.country = Region.find(request_params[:city]).country
      @request.save
    end
    respond_to do |format|
      if success
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    path = requests_url
    # If destroying a non-admin user's request, redirect to the admin path
    if current_user.is_admin and @request.user.id != current_user.id
      path = manage_all_requests_path
    end

    @request.destroy
    respond_to do |format|
      format.html { redirect_to path, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:user_id, :city, :country, :comments)
    end

    def require_admin
      unless current_user.is_admin?
        flash[:error] = "You must be an admin user to access regions."
        redirect_to sign_in_path
      end
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.error.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden-routes">
    <%= f.label :user_id %><br />
    <input class="form-control" type="number" name="request[user_id]" id="request_user_id" value="<%= current_user.id %>">
  </div>

  <p>The city for which you would like to view all distributions. If not listed, please include city name in comments below.</p>

  <div class="form-group">
    <%= f.label :city %>&nbsp;&nbsp;&nbsp;
     <%= f.collection_select :city, Region.order(:name), :id, :name, include_blank: true, :class => "form-control" %>
  </div>

  <div class="form-group hidden-routes">
    <%= f.label :country %>
    <%= f.text_field :country, :class => "form-control", :value => 'default' %>
  </div>

  
  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, :class => "form-control"  %>
  </div>

  <div class="form-actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

<br />

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Pending Requests</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Request Date</th>
      <th>City</th>
      <th>Country</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.created_at %></td>
        <td><%= Region.find(request.city).name %></td>
        <td><%= request.country %></td>
        <td><%= request.comments %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path, :class => "btn btn-info" %>

app/views/requests/manage_all.html.erb
<h1>All Pending Requests</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Request Date</th>
      <th>User</th>
      <th>City</th>
      <th>Country</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.created_at %></td>
        <td><%= request.user.firstname %> <%= request.user.lastname %></td>
        <td><%= Region.find(request.city).name %></td>
        <td><%= request.country %></td>
        <td><%= request.comments %></td>
        <td><%= link_to 'Approve', approve_requests_path(request) %></td>
        <td><%= link_to 'Reject', request, method: :delete, data: { confirm: 'Are you sure? Request will be deleted.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path, :class => "btn btn-info" %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<p>
  <strong>City:</strong>
  <%= Region.find(@request.city).name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @request.country %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @request.comments %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>