config/routes.rb
Rails.application.routes.draw do
  

  resources :requests do
    collection do
      get 'manage_all'
      get 'approve/:id' => :approve, as: 'approve'
    end
  end

  resources :regions do
    collection do
      get 'manage_all'
    end
  end

  resources :users do
    collection do
      get 'show/:id' => :show, as: 'show'
      get 'edit/:id' => :edit, as: 'edit'
      patch 'update/:id' => :update, as: 'update'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	resources :distributions


	root 'welcome#index'
  get '/about', to: "welcome#about"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eptah</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <!-- Click the site name to return to home page. -->
	      <!-- <a class="navbar-brand" href="#">Eptah</a> -->
	      <%= link_to "Eptah", root_path, :class => "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	    	<% if signed_in? %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Distributions <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to "View all", distributions_path %></li>
		            <% if current_user.default_region %>
			            <li><%= link_to "New distribution", new_distribution_path %></li>
			        <% end %>
		          </ul>
		        </li>
	        <% end %>
	        <% if signed_in? %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cities <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to "My cities", regions_path %></li>
		            <li><%= link_to "Request to join new city", new_request_path %></li>
		            <li><%= link_to "Pending requests", requests_path %></li>
		          </ul>
		        </li>
	        <% end %>
	        <% if signed_in? %>
		    	<% if current_user.is_admin? %>
			        <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><%= link_to "Manage all cities", manage_all_regions_path %></li>
			            <li><%= link_to "New city", new_region_path %></li>
			            <li><%= link_to "Manage city requests", manage_all_requests_path %></li>
			          </ul>
			        </li>
			    <% end %>
			    <!-- Signed in but not admin -->
			    <li><%= link_to "User Settings", user_path(:id => current_user.id) %></li>
	        <% end %>
	        <li><%= link_to "About & Contact", about_path %></li>
	      </ul>

	      <form class="navbar-form navbar-right">
	      	<div class="form-group">
		  		<!-- if logged in, display log out option and greeting -->
		      	<% if signed_in? %>
		      		Welcome, <%= current_user.firstname %>   || 
					<%= link_to 'Log out', sign_out_path, method: :delete %>
				<% else %>
				<!-- if not logged in, display link to login page -->
					<%= link_to 'Login or create new account', sign_in_path %>
				<% end %>
			</div>
	      </form>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<div class="container-fluid">

		<% flash.each do |key, value| %>
			<div id="flash" class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<div class="flash <%= key %>"><%= value %></div>
			</div>
		<% end %>
    	<%= yield %>
    </div>
  </body>
</html>